### ISSUE TITLE
Config management solutions for our secrets and connection credentials

### ISSUE THREAD

**Issue by dolfolife** [vmware-tanzu/streaming-runtimes#7]
We support a lot of information people might treat them carefully and without a lot of visibility. Currently, we do not have a way to obscure this information. 

We should provide a way to let users securely configure and manage their resources (e.g. Kafka, rabbitMQ).

**Comment by tzolov** [comment]
Initial solution based on service-binding spec is implemented and supported:
https://vmware-tanzu.github.io/streaming-runtimes/architecture/service-binding/service-binding/
